# Databricks notebook source
# MAGIC %pip install git+https://github.com/databrickslabs/dbldatagen@current

# COMMAND ----------

# MAGIC %pip install "databricks-sql-connector[sqlalchemy]"

# COMMAND ----------

from pyspark.sql.types import StringType
from pyspark.sql.functions import col, expr
import dbldatagen as dg
import random
from sqlalchemy import create_engine




airport_codes = [
    "AAL", "ABE", "ABQ", "ABV", "ABZ", "ACC", "ACE", "ACK", "ADA", "ADB",
    "ADD", "ADL", "ADQ", "ADS", "AEP", "AER", "AFW", "AGP", "AHB", "AKL",
    "ALA", "ALB", "ALC", "ALG", "AMA", "AMD", "AMM", "AMS", "ANC", "ANF",
    "ANU", "APA", "AQP", "ARN", "ATH", "ATL", "AUA", "AUH", "AUS", "AVL",
    "AXT", "AYT", "BAH", "BAQ", "BAV", "BBU", "BCD", "BCN", "BDJ", "BDL",
    "BDO", "BEG", "BEL", "BEN", "BER", "BET", "BEY", "BFI", "BFS", "BGI",
    "BGO", "BGW", "BGY", "BHD", "BHM", "BHX", "BIL", "BIO", "BJX", "BJY",
    "BKI", "BKK", "BKL", "BLA", "BLL", "BLQ", "BLR", "BMA", "BNA", "BNE",
    "BOD", "BOG", "BOI", "BOM", "BOO", "BOS", "BPN", "BRE", "BRI", "BRS",
    "BRU", "BSB", "BSL", "BTH", "BTR", "BTV", "BUD", "BUF", "BUR", "BVA",
    "BWI", "BWN", "BZE", "CAE", "CAG", "CAI", "CAK", "CAN", "CBB", "CBR",
    "CCJ", "CCS", "CCU", "CDG", "CEB", "CGB", "CGH", "CGK", "CGN", "CGO",
    "CGP", "CGQ", "CGR", "CHA", "CHC", "CHO", "CHS", "CIA", "CID", "CJU",
    "CKG", "CLE", "CLO", "CLT", "CMB", "CMH", "CMN", "CNF", "CNS", "CNX",
    "COK", "COR", "COS", "CPH", "CPT", "CRL", "CRP", "CRW", "CSX", "CTA",
    "CTG", "CTS", "CTU", "CUK", "CUL", "CUN", "CUR", "CUU", "CUZ", "CVG",
    "CWB", "CXH", "CYC", "CZX", "DAC", "DAD", "DAL", "DAR", "DAY", "DCA",
    "DEL", "DEN", "DFW", "DGA", "DJJ", "DKR", "DLA", "DLC", "DME", "DMK",
    "DMM", "DOH", "DPA", "DPS", "DRS", "DRW", "DSM", "DSN", "DTW", "DUB",
    "DUR", "DUS", "DVO", "DXB", "EBB", "EBH", "EBL", "ECP", "EDI", "EIN",
    "EIS", "ELP", "EMA", "ENA", "EOH", "ESB", "EUG", "EVN", "EWR", "EYW",
    "EZE", "FAI", "FAO", "FAR", "FAT", "FCO", "FLL", "FLN", "FLR", "FOC",
    "FOR", "FRA", "FRU", "FSD", "FTY", "FUE", "FUK", "FWA", "GAU", "GCI",
    "GDL", "GDN", "GEG", "GFK", "GIG", "GJT", "GLA", "GMP", "GOI", "GOT",
    "GRB", "GRO", "GRR", "GRU", "GRZ", "GSO", "GSP", "GUA", "GUM", "GVA",
    "GYD", "GYE", "GYN", "HAJ", "HAK", "HAM", "HAN", "HAV", "HBA", "HDY",
    "HEH", "HEL", "HET", "HFE", "HGH", "HHN", "HIJ", "HKG", "HKT", "HMO",
    "HND", "HNL", "HOU", "HPN", "HRB", "HSV", "HYA", "HYD", "IAD", "IAH",
    "IBZ", "ICN", "ICT", "IEV", "IKA", "IKT", "ILM", "ILO", "INC", "IND",
    "IOM", "ISB", "ISG", "ISL", "ISP", "IST", "ITM", "ITO", "IVG", "JAI",
    "JAN", "JAX", "JBQ", "JED", "JER", "JFK", "JHB", "JHG", "JJN", "JNB",
    "JNU", "JOG", "JRO", "KBL", "KBP", "KBR", "KCH", "KEF", "KGL", "KHH",
    "KHI", "KHN", "KIJ", "KIX", "KJA", "KKJ", "KLO", "KMG", "KMI", "KMJ",
    "KMQ", "KNO", "KOA", "KOJ", "KRK", "KRR", "KRS", "KRT", "KTM", "KTN",
    "KTW", "KUF", "KUL", "KWE", "KWI", "KWL", "KZN", "LAD", "LAN", "LAS",
    "LAX", "LBA", "LBB", "LCA", "LCK", "LCY", "LED", "LEJ", "LEX", "LGA",
    "LGB", "LGK", "LGW", "LHE", "LHR", "LHW", "LIH", "LIL", "LIM", "LIN",
    "LIRI", "LIS", "LIT", "LJG", "LJU", "LKO", "LLA", "LOP", "LOS", "LPA",
    "LPB", "LPL", "LST", "LTN", "LUN", "LUX", "LWM", "LYS", "LYVR", "MAA",
    "MAD", "MAF", "MAH", "MAN", "MAO", "MAR", "MBA", "MBJ", "MCI", "MCO",
    "MCT", "MCZ", "MDC", "MDE", "MDL", "MDT", "MDW", "MDZ", "MED", "MEL",
    "MEM", "MEX", "MFM", "MFR", "MHD", "MHT", "MIA", "MID", "MKC", "MKE",
    "MKK", "MLA", "MLE", "MLI", "MMX", "MNL", "MOB", "MPH", "MPL", "MPM",
    "MRS", "MRU", "MRV", "MRY", "MSN", "MSP", "MSQ", "MSY", "MTY", "MUC",
    "MVD", "MVY", "MXP", "MYJ", "MYR", "MYY", "NAN", "NAP", "NAS", "NAT",
    "NAY", "NBO", "NCE", "NCL", "NGB", "NGO", "NGQ", "NGS", "NKG", "NNG",
    "NRN", "NRT", "NSN", "NTE", "NTL", "NUE", "NYO", "OAK", "OGG", "OIT",
    "OKA", "OKC", "OMA", "OME", "ONT", "OOL", "OPO", "ORD", "ORF", "ORL",
    "ORY", "OSL", "OTP", "OTZ", "OVB", "PBI", "PDG", "PDK", "PDX", "PEK",
    "PEN", "PER", "PFO", "PHC", "PHL", "PHX", "PIA", "PIT", "PKU", "PLJ",
    "PLM", "PLS", "PLU", "PLZ", "PMI", "PMO", "PMV", "PNH", "PNK", "PNQ",
    "PNS", "POA", "POM", "POS", "PRG", "PSA", "PSP", "PTP", "PTY", "PUJ",
    "PUS", "PVD", "PVG", "PWM", "RAK", "RAO", "RDM", "RDU", "REC", "REP",
    "RGN", "RIC", "RIX", "RNO", "ROA", "ROC", "ROV", "RST", "RSW", "RTM",
    "RUH", "RYG", "SAH", "SAL", "SAN", "SAP", "SAT", "SAV", "SAW", "SBA",
    "SBH", "SBN", "SBW", "SCL", "SDF", "SDJ", "SDQ", "SDU", "SEA", "SFO",
    "SGF", "SGN", "SHA", "SHE", "SHJ", "SHV", "SIN", "SJC", "SJD", "SJO",
    "SJU", "SJW", "SKG", "SLC", "SLZ", "SMF", "SNA", "SOF", "SOU", "SPN",
    "SPR", "SRG", "SSA", "SSH", "STL", "STN", "STP", "STR", "STT", "STX",
    "SUB", "SUS", "SVG", "SVO", "SVQ", "SVX", "SWA", "SXB", "SXM", "SXR",
    "SYD", "SYR", "SYX", "SYZ", "SZB", "SZG", "SZX", "TAO", "TAS", "TEB",
    "TFN", "TFS", "THQ", "THR", "TIA", "TIJ", "TIP", "TJM", "TLH", "TLL",
    "TLS", "TLV", "TNA", "TOS", "TPA", "TPE", "TRD", "TRF", "TRN", "TRV",
    "TSA", "TSE", "TSN", "TSV", "TUL", "TUN", "TUS", "TYN", "TYS", "TZA",
    "TZX", "UBN", "UFA", "UIO", "UKB", "UME", "UPG", "URC", "USM", "UYN",
    "UZC", "VCE", "VCP", "VDO", "VER", "VIE", "VIX", "VKO", "VLC", "VNO",
    "VQS", "VRN", "VSA", "VTE", "VVI", "WAW", "WLG", "WMX", "WNZ", "WRO",
    "WUH", "WUX", "XIY", "XMN", "XNA", "XNN", "XQC", "YDF", "YEG", "YHM",
    "YHZ", "YIP", "YKS", "YLW", "YMM", "YNT", "YOW", "YPA", "YQB", "YQM",
    "YQR", "YQT", "YSB", "YTH", "YTS", "YTZ", "YUL", "YUM", "YVR", "YWG",
    "YWK", "YXE", "YXL", "YYC", "YYJ", "YYR", "YYT", "YYZ", "YZF", "YZV",
    "ZAG", "ZBK", "ZNZ", "ZRH", "ZUH"
]


airport_names = [
    'Aalborg Airport',
    'Lehigh Valley International Airport',
    'Albuquerque International Sunport',
    'Nnamdi Azikiwe International Airport',
    'Aberdeen International Airport',
    'Kotoka International Airport',
    'Lanzarote Airport',
    'Nantucket Memorial Airport',
    'Adana Sakirpasa Airport',
    'Izmir Adnan Menderes Airport',
    'Addis Ababa Bole International Airport',
    'Adelaide Airport',
    'Kodiak Benny Benson State Airport',
    'Addison Airport',
    'Jorge Newbery Airport',
    'Sochi International Airport',
    'Fort Worth Alliance Airport',
    'Malaga Airport',
    'Abha Regional Airport',
    'Auckland Airport',
    'Almaty Airport',
    'Albany International Airport',
    'Alicante-Elche Airport',
    'Houari Boumediene Airport',
    'Rick Husband Amarillo International Airport',
    'Ahmedabad Airport',
    'Queen Alia International Airport',
    'Amsterdam Airport Schiphol',
    'Ted Stevens Anchorage International Airport',
    'Cerro Moreno International Airport',
    'V.C. Bird International Airport',
    'Centennial Airport',
    'Rodriguez Ballon International Airport',
    'Stockholm Arlanda Airport',
    'Eleftherios Venizelos International Airport',
    'Hartsfield-Jackson Atlanta International Airport',
    'Reina Beatrix International Airport',
    'Abu Dhabi International Airport',
    'Austin-Bergstrom International Airport',
    'Asheville Regional Airport',
    'Akita Airport',
    'Antalya Airport',
    'Bahrain International Airport',
    'Ernesto Cortissoz International Airport',
    'Baotou Airport',
    'Baneasa Airport',
    'Silay International Airport',
    'Barcelona-El Prat Airport',
    'Syamsudin Noor International Airport',
    'Bradley International Airport',
    'Husein Sastranegara Airport',
    'Belgrad Nikola Tesla Airport',
    'Val De Cans International Airport',
    'Benina International Airport',
    'Berlin Brandenburg Airport',
    'Bethel Airport',
    'Beirut-Rafic Hariri International Airport',
    'Boeing Field International Airport',
    'Belfast International Airport',
    'Grantley Adams International Airport',
    'Bergen Airport',
    'Baghdad International Airport',
    'Orio al Serio International Airport',
    'George Best Belfast City Airport',
    'Birmingham-Shuttlesworth International Airport',
    'Birmingham International Airport',
    'Billings Logan International Airport',
    'Bilbao Airport',
    'Del Bajio International Airport',
    'Batajnica Airbase',
    'Kota Kinabalu International Airport',
    'Suvarnabhumi Airport',
    'Burke Lakefront Airport',
    'General Jose Antonio Anzoategui International Airport',
    'Billund Airport',
    'Guglielmo Marconi Airport',
    'Kempegowda International Airport',
    'Bromma Airport',
    'Nashville International Airport',
    'Brisbane Airport',
    'Bordeaux Airport',
    'El Dorado International Airport',
    'Boise Air Terminal (Gowen Field)',
    'Chhatrapati Shivaji Maharaj International Airport',
    'Bodo Airport',
    'Logan International Airport',
    'Sultan Aji Muhamad Sulaiman Airport',
    'Bremen Airport',
    'Palese Airport',
    'Bristol Airport',
    'Brussels Airport',
    'Brasilia International Airport',
    'EuroAirport Swiss',
    'Hang Nadim International Airport',
    'Baton Rouge Metropolitan Airport',
    'Burlington International Airport',
    'Budapest Ferenc Liszt International Airport',
    'Buffalo Niagara International Airport',
    'Bob Hope Airport',
    'Beauvais-Tille Airport',
    'Baltimore/Wash International Thurgood Marshall Airport',
    'Brunei International Airport',
    'Philip S.W. Goldson International Airport',
    'Columbia Metropolitan Airport',
    'Cagliari Elmas Airport',
    'Cairo International Airport',
    'Akron-Canton Airport',
    'Guangzhou Baiyun International Airport',
    'J Wilsterman Airport',
    'Canberra Airport',
    'Calicut International Airport',
    'Simon Bolivar International Airport',
    'Netaji Subhas Chandra Bose Airport',
    'Charles de Gaulle Airport',
    'Mactan-Cebu International Airport',
    'Marechal Rondon International Airport',
    'Sao Paulo/Congonhas Airport',
    'Soekarno-Hatta International Airport',
    'Cologne Bonn Airport',
    'Zhengzhou Xinzheng Airport',
    'Shah Amanat International Airport',
    'Changchun Longjia International Airport',
    'Campo Grande International Airport',
    'Chattanooga Airport',
    'Christchurch International Airport',
    'Charlottesville Albemarle Airport',
    'Charleston International Airport',
    'Ciampino-G. B. Pastine International Airport',
    'The Eastern Iowa',
    'Cleveland Hopkins International Airport',
    'Alfonso B. Aragon Airport',
    'Charlotte Douglas International Airport',
    'Bandaranaike International Airport',
    'John Glenn Columbus International Airport',
    'Mohamed V International Airport',
    'Tancredo Neves International Airport',
    'Cairns Airport',
    'Chiang Mai International Airport',
    'Cochin International Airport',
    'Ingeniero Aeronautico Ambrosio L.V. Taravella International Airport',
    'Colorado Springs Municipal Airport',
    'Copenhagen Airport',
    'Cape Town International Airport',
    'Brussels S. Charleroi Airport',
    'Corpus Christi International Airport',
    'Yeager Airport',
    'Changsha Huanghua Airport',
    'Catania-Fontanarossa Airport',
    'Rafael Nunez International Airport',
    'New Chitose Airport',
    'Chengdu Shuangliu International Airport',
    'Caye Caulker Airport',
    'Culiacan International Airport',
    'Cancun International Airport',
    'Hato International Airport',
    'Gen Fierro Villalobos Airport',
    'Alejandro Velasco Astete International Airport',
    'Cincinnati/Northern Kentucky Airport',
    'Afonso Pena International Airport',
    'Vancouver Harbour Sea Plane Base',
    'Caye Chapel Airport',
    'Changzhou Airport',
    'Hazrat Shahjalal International Airport',
    'Da Nang International Airport',
    'Dallas Love Field',
    'Julius Nyerere International Airport',
    'James M. Cox Dayton International Airport',
    'Ronald Reagan National Airport',
    'Indira Gandhi International Airport',
    'Denver International Airport',
    'Dallas/Fort Worth International Airport',
    'Dangriga Airport',
    'Sentani Airport',
    'Leopold Sedar Senghor International Airport',
    'Douala Airport',
    'Dalian Zhoushuizi International Airport',
    'Moscow Domodedovo Airport',
    'Don Mueang International Airport',
    'King Fahd International Airport',
    'Hamad International Airport',
    'DuPage Airport',
    'Ngurah Rai International Airport',
    'Dresden International Airport',
    'Darwin International Airport',
    'Des Moines International Airport',
    'Ordos Ejin Horo Airport',
    'Detroit Metropolitan Wayne County Airport',
    'Dublin Airport',
    'King Shaka International Airport',
    'Dusseldorf International Airport',
    'Francisco Bangoy Intl Airport',
    'Dubai Airport',
    'Entebbe International Airport',
    'El Bayadh Airport',
    'Erbil International Airport',
    'Northwest Florida Beaches International Airport',
    'Edinburgh Airport',
    'Eindhoven Airport',
    'Terrance B. Lettsome International Airport',
    'El Paso International Airport',
    'East Midlands Airport',
    'Kenai Municipal Airport',
    'Enrique Olaya Herrera Airport',
    'Esenboga International Airport',
    'Mahlon Sweet Field',
    'Zvartnots International Airport',
    'Newark Liberty International Airport',
    'Key West International Airport',
    'Ministro Pistarini Airport',
    'Fairbanks International Airport',
    'Faro Airport',
    'Hector International Airport',
    'Fresno Yosemite International Airport',
    'Leonardo da Vinci-Fiumicino Airport',
    'Fort Lauderdale-Hollywood International Airport',
    'Hercilio Luz International Airport',
    'Firenze-Peretola Airport',
    'Changle International Airport',
    'Pinto Martins Airport',
    'Frankfurt Airport',
    'Manas International Airport',
    'Joe Foss Field',
    'Fulton County Airport',
    'Fuerteventura Airport',
    'Fukuoka Airport',
    'Fort Wayne International Airport',
    'Lokpriya Gopinath Bordoloi International Airport',
    'Guernsey Airport',
    'Miguel Hidalgo y Costilla International Airport',
    'Gdansk Lech Walesa Airport',
    'Spokane International Airport',
    'Grand Forks International Airport',
    'Galeao Antonio Carlos Jobim International Airport',
    'Grand Junction Regional Airport',
    'Glasgow International Airport',
    'Gimpo International Airport',
    'Dabolim Airport',
    'Goteborg Landvetter Airport',
    'Austin Straubel International Airport',
    'Girona-Costa Brava Airport',
    'Gerald R. Ford International Airport',
    'Sao Paulo-Guarulhos International Airport',
    'Graz Airport',
    'Piedmont Triad International Airport',
    'Greenville-Spartanburg International Airport',
    'La Aurora International Airport',
    'A.B. Won Pat International Airport',
    'Geneve Airport',
    'Heydar Aliyev International Airport',
    'Jose Joaquin de Olmedo Airport',
    'Santa Genoveva Airport',
    'Hannover Airport',
    'Haikou Meilan International Airport',
    'Hamburg Airport',
    'Noi Bai International Airport',
    'Jose Marti International Airport',
    'Hobart International Airport',
    'Hat Yai International Airport',
    'Heho Airport',
    'Helsinki-Vantaa Airport',
    'Hohhot Baita International Airport',
    'Hefei Xinqiao Airport',
    'Hangzhou Xiaoshan International Airport',
    'Frankfurt - Hahn Airport',
    'Hiroshima Airport',
    'Hong Kong International Airport',
    'Phuket International Airport',
    'Gen Pesqueira Garcia Airport',
    'Haneda Airport',
    'Daniel K. Inouye International Airport',
    'William P. Hobby Airport',
    'Westchester County Airport',
    'Harbin Taiping International Airport',
    'Huntsville International Airport - Carl T. Jones Field',
    'Barnstable Municipal Airport',
    'Rajiv Gandhi International Airport',
    'Washington Dulles International Airport',
    'George Bush Intercontinental Airport',
    'Ibiza Airport',
    'Incheon International Airport',
    'Wichita Dwight D. Eisenhower National Airport',
    'Kyiv International Airport',
    'Imam Khomeini International Airport',
    'Irkutsk International Airport',
    'Wilmington International Airport',
    'Iloilo International Airport',
    'Yinchuan Hedong International Airport',
    'Indianapolis International Airport',
    'Isle of Man Airport',
    'Islamabad International Airport',
    'Painushima Ishigaki Airport',
    'Istanbul Airport',
    'Long Island MacArthur Airport',
    'Istanbul Ataturk Airport',
    'Osaka International Airport',
    'Hilo International Airport',
    'Berane-Ivangrad Airport',
    'Jaipur Airport',
    'Jackson-Evers International Airport',
    'Jacksonville International Airport',
    'Dr. Joaquin Balaguer International Airport',
    'King Abdulaziz International Airport',
    'Jersey Airport',
    'John F. Kennedy International Airport',
    'Senai Airport',
    'Xishuangbanna Gasa Airport',
    'Quanzhou Jinjiang International Airport',
    'O.R. Tambo International Airport',
    'Juneau International Airport',
    'Adisutjipto International Airport',
    'Kilimanjaro International Airport',
    'Kabul International Airport',
    'Boryspil International Airport',
    'Sultan Ismail Petra Airport',
    'Kuching International Airport',
    'Keflavik International Airport',
    'Kigali International Airport',
    'Kaohsiung International Airport',
    'Jinnah International Airport',
    'Nanchang Changbei International Airport',
    'Niigata Airport',
    'Kansai International Airport',
    'Krasnoyarsk Airport',
    'Kitakyushu Airport',
    'Kalibo International Airport',
    'Kunming Changshui International Airport',
    'Miyazaki Airport',
    'Kumamoto Airport',
    'Komatsu Airport',
    'Kuala Namu International Airport',
    'Kona International Airport at Keahole',
    'Kagoshima Airport',
    'J. Paul II International Airport Krakow-Balice',
    'Krasnodar International Airport',
    'Kristiansand Airport',
    'Khartoum International Airport',
    'Tribhuvan International Airport',
    'Ketchikan International Airport',
    'Katowice International Airport',
    'Kurumoch International Airport',
    'Kuala Lumpur International Airport',
    'Guiyang Longdongbao International Airport',
    'Kuwait International Airport',
    'Guilin Liangjiang International Airport',
    'Kazan International Airport',
    'Quatro de Fevereiro Airport',
    'Lansing Capital Region International Airport',
    'Harry Reid International Airport',
    'Los Angeles International Airport',
    'Leeds Bradford International Airport',
    'Lubbock Preston Smith International Airport',
    'Larnaca International Airport',
    'Rickenbacker International Airport',
    'London City Airport',
    'Pulkovo Airport',
    'Leipzig/Halle Airport',
    'Blue Grass Airport',
    'LaGuardia Airport',
    'Long Beach Airport',
    'Langkawi International Airport',
    'London Gatwick Airport',
    'Allama Iqbal International Airport',
    'London Heathrow Airport',
    'Lanzhou Zhongchuan International Airport',
    'Lihue Airport',
    'Lille Airport',
    'Jorge Chavez International Airport',
    'Milano Linate Airport',
    'Salerno Costa d\'Amalfi',
    'Los Cabos International Airport',
    'Alejandro Velasco Astete International Airport',
    'Capitan FAP Carlos Martinez de Pinillos International Airport',
    'Jorge Chavez International Airport',
    'Rodriguez Ballon International Airport',
    'Fernando Belaunde Terry Airport',
    'Cancun International Airport',
    'Licenciado Benito Juarez International Airport',
    'Chub Cay International Airport',
    'Lynden Pindling International Airport',
    'Clorinda Airport',
    'Malvinas Argentinas International Airport',
    'Brigadier Mayor D Cesar Raul Ojeda Airport',
    'Corrientes Airport',
    'Cataratas del Iguazu International Airport',
    'Chileka International Airport',
    'Cheddi Jagan International Airport',
    'La Chorrera Airport',
    'Chichen Itza International Airport',
    'Kabri Dar Airport',
    'Canefield Airport',
    'Cyril E. King Airport',
    'San Cristobal Airport',
    'Cunagua Airport',
    'Cape Dorset Airport',
    'Cardinal Bernardin Gantin International Airport',
    'Calicut International Airport',
    'Netaji Subhash Chandra Bose International Airport',
    'Chitose Air Base',
    'Tribhuvan International Airport',
    'Chengdu Shuangliu International Airport',
    'Changchun Longjia International Airport',
    'Zhoushuizi Airport',
    'Changsha Huanghua International Airport',
    'Tullamarine Airport',
    'Qingdao Liuting International Airport',
    'Chongqing Jiangbei International Airport',
    'Capodichino Airport',
    'Cape Town International Airport',
    'Presidente Juscelino Kubistschek International Airport',
    'Camilo Daza International Airport',
    'Cork Airport',
    'Charles De Gaulle International Airport',
    'Carriel Sur Airport',
    'Ministro Pistarini International Airport',
    'Buenos Aires International Airport',
    'Rafael Nunez International Airport',
    'Jose Maria Cordova International Airport',
    'Mariscal Sucre International Airport',
    'Cat Bi International Airport',
    'Chubu Centrair International Airport',
    'Rafic Hariri International Airport',
    'Dulles International Airport',
    'Detroit Metropolitan Wayne County Airport',
    'Ninoy Aquino International Airport',
    'Kuala Lumpur International Airport',
    'Dubai International Airport',
    'Don Mueang International Airport',
    'Suvarnabhumi Airport',
    'Ernst Happel International Airport',
    'Cork International Airport',
    'M.R. Stefanik Airport',
    'Dublin Airport',
    'Kotoka International Airport',
    'Husein Sastranegara International Airport',
    'Kempegowda International Airport',
    'Kempegowda International Airport',
    'Kempegowda International Airport',
    'Hong Kong International Airport',
    'Los Angeles International Airport',
    'Macon Downtown Airport',
    'Macon Downtown Airport',
    'Mar Del Plata Airport',
    'Mason City Municipal Airport',
    'Mason City Municipal Airport',
    'Manchester Airport',
    'Miguel Hidalgo Y Costilla International Airport',
    'Mohammed V International Airport',
    'Munich International Airport',
    'General Mitchell International Airport',
    "Molokai Airport",
    "Malta International Airport",
    "Velana International Airport",
    "Quad City International Airport",
    "Malmo Airport",
    "Ninoy Aquino International Airport",
    "Mobile Regional Airport",
    "Godofredo P. Ramos Airport",
    "Montpellier Mediterranee Airport",
    "Maputo International Airport",
    "Marseille Provence Airport",
    "Sir Seewoosagur Ramgoolam International Airport",
    "Mineralnye Vody Airport",
    "Monterey Regional Airport",
    "Dane County Regional Airport",
    "Minneapolis-St. Paul International Airport",
    "Minsk National Airport",
    "Louis Armstrong New Orleans International Airport",
    "Gen Mariano Escobedo Airport",
    "Franz Josef Strauss Airport",
    "Carrasco International Airport",
    "Martha's Vineyard Airport",
    "Milano Malpensa Airport",
    "Matsuyama Airport",
    "Myrtle Beach International Airport",
    "Miri Airport",
    "Nadi International Airport",
    "Naples International Airport",
    "Lynden Pindling International Airport",
    "Sao Goncalo do Amarante-Governador Aluizio Alves Intl Airport",
    "Beijing Nanyuan Airport",
    "Jomo Kenyatta International Airport",
    "Cote D'Azur Airport",
    "Newcastle International Airport",
    "Ningbo Lishe International Airport",
    "Chubu Centrair International Airport",
    "Ngari Gunsa/Ali Kunsha Airport",
    "Nagasaki Airport",
    "Nanjing Lukou International Airport",
    "Nanning Airport",
    "Weeze Airport",
    "Narita International Airport",
    "Nelson Airport",
    "Nantes Atlantique Airport",
    "Newcastle Airport",
    "Nuremberg Airport",
    "Stockholm Skavsta Airport",
    "Metropolitan Oakland International Airport",
    "Kahului Airport",
    "Oita Airport",
    "Naha Airport",
    "Will Rogers World Airport",
    "Eppley Airfield",
    "Nome Airport",
    "Ontario International Airport",
    "Gold Coast Airport",
    "Porto Airport",
    "O'Hare International Airport",
    "Norfolk International Airport",
    "Orlando Executive Airport",
    "Paris Orly Airport",
    "Oslo Airport Gardermoen",
    "Bucharest Henri Coanda International Airport",
    "Ralph Wien Memorial Airport",
    "Novosibirsk Tolmachevo Airport",
    "Palm Beach International Airport",
    "Minangkabau International Airport",
    "DeKalb Peachtree Airport",
    "Portland International Airport",
    "Beijing Capital International Airport",
    "Penang International Airport",
    "Perth Airport",
    "Paphos International Airport",
    "Port Harcourt International Airport",
    "Philadelphia International Airport",
    "Phoenix Sky Harbor International Airport",
    "Peoria International Airport",
    "Pittsburgh International Airport",
    "Sultan Syarif Kasim II International Airport",
    "Placencia Airport",
    "Sultan Mahmud Badaruddin II Airport",
    "Providenciales International Airport",
    "Pampulha Airport",
    "Port Elizabeth International Airport",
    "Palma de Mallorca Airport",
    "Falcone-Borsellino Airport",
    "Santiago Marino International Airport",
    "Phnom Penh International Airport",
    "Supadio International Airport",
    "Pune Airport",
    "Pensacola International Airport",
    "Salgado Filho International Airport",
    "Jacksons International Airport",
    "Piarco International Airport",
    "Vaclav Havel Airport Prague",
    "Pisa International Airport",
    "Palm Springs International Airport",
    "Pointe-a-Pitre Le Raizet Airport",
    "Tocumen International Airport",
    "Punta Cana International Airport",
    "Gimhae International Airport",
    "Theodore Francis Green Memorial State Airport",
    "Shanghai Pudong International Airport",
    "Portland International Jetport",
    "Menara Airport",
    "Dr. Leite Lopes State Airport",
    "Roberts Field",
    "Raleigh-Durham International Airport",
    "Guararapes-Gilberto Freyre International Airport",
    "Siem Reap International Airport",
    "Yangon International Airport",
    "Richmond International Airport (Byrd Field)",
    "Riga International Airport",
    "Reno/Tahoe International Airport",
    "Roanoke-Blacksburg Regional Airport",
    "Greater Rochester International Airport",
    "Platov International Airport",
    "Rochester International Airport",
    "Southwest Florida International Airport",
    "Rotterdam The Hague Airport",
    "King Khalid International Airport",
    "Moss-Rygge Airport",
    "Sana'a International Airport",
    "El Salvador International Airport",
    "San Diego International Airport",
    "Ramon Villeda Morales International Airport",
    "San Antonio International Airport",
    "Savannah/Hilton Head Airport",
    "Sabiha Gokcen International Airport",
    "Santa Barbara Municipal Airport",
    "St. Barthelemy Airport",
    "South Bend Regional",
    "Sibu Airport",
    "Arturo Merino Benitez Airport",
    "Louisville International Airport-Standiford Field",
    "Sendai Airport",
    "Las Americas International Airport",
    "Santos Dumont Airport",
    "Seattle-Tacoma International Airport",
    "San Francisco International Airport",
    "Springfield-Branson National Airport",
    "Tan Son Nhat International Airport",
    "Shanghai Hongqiao International Airport",
    "Shenyang Taoxian International Airport",
    "Sharjah International Airport",
    "Shreveport Regional Airport",
    "Changi International Airport",
    "Norman Y. Mineta San Jose International Airport",
    "Los Cabos International Airport",
    "Juan Santamaria International Airport",
    "Luis Munoz Marin International Airport",
    "Shijiazhuang Zhengding International Airport",
    "Thessaloniki International Airport",
    "Salt Lake City International Airport",
    "Marechal Cunha Machado International Airport",
    "Sacramento International Airport",
    "John Wayne Airport",
    "Sofia Airport",
    "Southampton Airport",
    "Francisco C. Ada International Airport",
    "San Pedro Airport",
    "Achmad Yani International Airport",
    "Deputado Luis Eduardo Magalhaes International Airport",
    "Sharm El Sheikh Airport",
    "Lambert-St. Louis International Airport",
    "Stansted Airport",
    "St. Paul Downtown Airport",
    "Stuttgart Airport",
    "Cyril E. King Airport",
    "Henry E. Rohlsen Airport",
    "Juanda International Airport",
    "Spirit of St. Louis Airport",
    "Stavanger Airport Sola",
    "Sheremetyevo International Airport",
    "Seville Airport",
    "Koltsovo International Airport",
    "Jieyang Chaoshan Airport",
    "Strasbourg Airport",
    "Princess Juliana International Airport",
    "Srinagar International Airport",
    "Sydney (Kingsford Smith) Airport",
    "Hancock International Airport",
    "Sanya Phoenix International Airport",
    "Shiraz International Airport",
    "Sultan Abdul Aziz Shah Airport",
    "W. A. Mozart Salzburg Airport",
    "Shenzhen Bao'an International Airport",
    "Qingdao Jiaodong International Airport",
    "Tashkent International Airport",
    "Teterboro Airport",
    "Tenerife North Airport",
    "Tenerife South Airport",
    "Tianshui Maijishan Airport",
    "Mehrabad International Airport",
    "Tirana International Airport",
    "Tijuana Airport",
    "Tripoli International Airport",
    "Roshchino International Airport",
    "Tallahassee International Airport",
    "Tallinn Airport",
    "Toulouse-Blagnac Airport",
    "Ben Gurion International Airport",
    "Jinan Yaoqiang International Airport",
    "Tromso/Langnes Airport",
    "Tampa International Airport",
    "Taiwan Taoyuan International Airport",
    "Trondheim Airport Vaernes",
    "Torp Sandefjord Airport",
    "Turin Airport",
    "Trivandrum International Airport",
    "Taipei Songshan Airport",
    "Nur-Sultan Nazarbayev Airport",
    "Tianjin Binhai International Airport",
    "Townsville Airport",
    "Tulsa International Airport",
    "Tunis-Carthage International Airport",
    "Tucson International Airport",
    "Taiyuan Wusu International Airport",
    "McGhee Tyson Airport",
    "Sir Barry Bowen Municipal Airport",
    "Trabzon Airport",
    "Chinggis Khan International Airport",
    "Ufa International Airport",
    "Mariscal Sucre International Airport",
    "Kobe Airport",
    "Umea Airport",
    "Sultan Hasanuddin International Airport",
    "Urumqi Diwopu International Airport",
    "Koh Samui Airport",
    "Yulin Yuyang Airport",
    "Ponikve Airport",
    "Venice Marco Polo Airport",
    "Viracopos Airport",
    "Van Don International Airport",
    "Veracruz International Airport",
    "Vienna International Airport",
    "Eurico de Aguiar Salles Airport",
    "Vnukovo Airport",
    "Valencia Airport",
    "Vilnius International Airport",
    "Antonio Rivera Rodriguez Airport",
    "Verona Villafranca Airport",
    "Carlos Rovirosa Perez International Airport",
    "Wattay International Airport",
    "Viru Viru International Airport",
    "Frederic Chopin Airport",
    "Wellington International Airport",
    "Wamena Airport",
    "Wenzhou Longwan International Airport",
    "Wroclaw Airport",
    "Wuhan Tianhe International Airport",
    "Sunan Shuofang International Airport",
    "Xianyang International Airport",
    "Xiamen Gaoqi International Airport",
    "Northwest Arkansas Regional Airport",
    "Xining Caojiabao Airport",
    "Balad Airbase",
    "Deer Lake Regional Airport",
    "Edmonton International Airport",
    "John C. Munro Hamilton Airport",
    "Halifax Stanfield International Airport",
    "Willow Run Airport",
    "Yakutsk Airport",
    "Kelowna International Airport",
    "Fort McMurray International Airport",
    "Penglai International Airport",
    "Ottawa/Macdonald-Cartier International Airport",
    "Glass Field",
    "Quebec City Jean Lesage International Airport",
    "Greater Moncton International Airport",
    "Regina International Airport",
    "Thunder Bay International Airport",
    "Sudbury Airport",
    "Thompson Airport",
    "Timmins Victor M. Power Airport",
    "Billy Bishop Toronto City Airport",
    "Montreal-Pierre Elliott Trudeau International Airport",
    "Yuma International Airport",
    "Vancouver International Airport",
    "Winnipeg James Armstrong Richardson International Airport",
    "Wabush Airport",
    "Saskatoon International Airport",
    "Sioux Lookout Airport",
    "Calgary International Airport",
    "Victoria International Airport",
    "Goose Bay Airport",
    "St. John's International Airport",
    "Pearson International Airport",
    "Yellowknife Airport",
    "Sept-Iles Airport",
    "Franjo Tudman Airport",
    "Zabljak Airport",
    "Abeid Amani Karume International Airport",
    "Zurich Airport",
    "Zhuhai Jinwan Airport"
]
    




type_ofFlight = ['Arrival' , 'Departure']





testDataSpec = (
    dg.DataGenerator(spark, name="airport_arrivals_statuses", rows=10000000, # rows oznacza ilość rzędów , możecie zmnienić ich generowaną ilość
                     partitions=8, randomSeedMethod='hash_fieldname')
    
    
    .withColumn("internal_airport_id", StringType(), values=airport_codes,
                baseColumnType="hash", omit=False)
    
    .withColumn("flight_id", "integer", minValue=100000000, maxValue=999999999,
                baseColumn="internal_airport_id",
                baseColumnType="hash", omit=False)
    
    .withColumn("type of flight", StringType(), values = type_ofFlight,
                baseColumn="internal_airport_id",
                baseColumnType="hash", omit=False)
    
    .withColumn("planned time of flight", "timestamp", begin="2023-05-30 01:00:00",
                baseColumn="internal_airport_id",
                end="2024-05-30 23:59:00",
                interval="1 minute", random=True)
    
    .withColumn("delay_time [minutes]", "integer", minValue=30, maxValue=1440,
                baseColumn="internal_airport_id",
                baseColumnType="hash", omit=False) # trochę dla picu , ale no funkcje działają tak sobie , więc średnio się da zrobić to rozkładem gaussa
)

dfTestData = testDataSpec.build()



airport_mapping_df = spark.createDataFrame(list(zip(airport_codes, airport_names)), schema=["fs", "airport_name"])


df_fixed = dfTestData.join(airport_mapping_df, dfTestData["internal_airport_id"] == airport_mapping_df["fs"], "left")

jdbc_url = "jdbc:postgresql://37.190.134.7:6800/FlightCenter"
connection_properties = {
    "user": "postgres",
    "password": "Vw8nQ0Sd9ewLHRoGE2eZ",
    "driver": "org.postgresql.Driver"
}

# Write the DataFrame to PostgreSQL
df_fixed.write.jdbc(url=jdbc_url, table="flight_stats", mode="overwrite", properties=connection_properties)

df_fixed.show(100, truncate=False)
df_fixed.printSchema()



df_fixed.write.format("json").mode("overwrite").save("/Project/JSONDATA")

